Neos:
  Flow:
    http:
      middlewares:
        'languageRedirect':
          middleware: 'Wegmeister\LanguageRedirect\Middleware\LanguageRedirectMiddleware'
          position: 'after trustedProxies'
